#! /bin/sh

set -e

if ! grep -q "^proxy:" /etc/passwd
then
        #
        #       Let's hope that this works; if /var/spool/squid is
        #       already present this fails :(
        #
        adduser --system --home /var/spool/squid --group proxy
        #
        # Change the shell so that cron jobs will work.
        # (They run as root now, but you can never know).
        #
        chsh -s /bin/sh proxy
fi

exit 0
